export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';

export const REGISTER = 'REGISTER';
export const FETCH_APPLICANTS = 'FETCH_APPLICANTS';
export const FETCH_APPLICANT = 'FETCH_APPLICANT';
export const CHANGE_STATUS = 'CHANGE_STATUS';

export const FETCH_DORMS = 'FETCH_DORMS';
export const ADD_BUILDING = 'ADD_BUILDING';
export const ADD_ROOM = 'ADD_ROOM';

export const OPEN_REGISTRATION = 'OPEN_REGISTRATION';
export const CLOSE_REGISTRATION = 'CLOSE_REGISTRATION';
export const FETCH_REGTIME = 'FETCH_REGTIME';

export const FETCH_ACTIVITIES = 'FETCH_ACTIVITIES';

export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

